"""
Pydantic schemas and shared enums.

Kept language-agnostic where possible so C/C++/Java compilers can plug in later.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Language(str, Enum):
    """Supported (or planned) source languages."""

    PYTHON = "python"
    CPP = "cpp"  # future
    C = "c"  # future
    JAVA = "java"  # future


class CompileRequest(BaseModel):
    """Request body for POST /compile."""

    code: str = Field(..., min_length=1, description="Source code to check")
    user_id: str = Field(..., min_length=1, description="Stable id for this learner")
    language: Language = Field(default=Language.PYTHON)


class CompileResponse(BaseModel):
    """Structured API response after compile / explain pipeline."""

    success: bool
    line_number: int | None = None
    error_type: str | None = None
    raw_error: str | None = None
    faulty_line: str | None = None
    explanation: str = ""
    rag_explanation: dict[str, str] = Field(default_factory=dict)
    rag_docs: list[dict[str, Any]] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    weak_topics: list[str] = Field(default_factory=list)
    common_errors: list[str] = Field(default_factory=list)


class UserStatsResponse(BaseModel):
    """Per-user learning / error profile for GET /user/{user_id}/stats."""

    user_id: str
    total_errors_recorded: int
    weak_topics: list[str]
    common_errors: list[str]
    topic_counts: dict[str, int]
    error_type_counts: dict[str, int]
    last_error_at: datetime | None = None


class CompileResult(BaseModel):
    """
    Internal result from a language-specific compiler/checker.

    When success is True, error_* fields are None.
    """

    success: bool
    language: Language
    error_type: str | None = None
    raw_error: str | None = None
    line_number: int | None = None
    faulty_line: str | None = None
    mapped_topic: str | None = None
    extra: dict[str, Any] = Field(default_factory=dict)


class QuestionResult(BaseModel):
    """Result of a single quiz question."""
    question_id: str
    topic: str
    concept: str | None = None
    is_correct: bool
    time_spent: float


class AnalysisRequest(BaseModel):
    """Request body for overall performance summarizing."""

    domain: str
    weak_topics: list[str]
    micro_gaps: list[str]
    root_cause: str
    results: list[QuestionResult] = Field(default_factory=list)


class QuestionAnalysis(BaseModel):
    """Deep-dive analysis of a single question's thought process."""
    question_id: str
    topic: str
    concept: str
    is_correct: bool
    mentor_thought_process: str
    key_takeaway: str


class AnalysisResponse(BaseModel):
    """Summarized learning strategy generated by AI."""

    summary: str
    reasoning_chain: list[str]
    detailed_report: list[QuestionAnalysis] = Field(default_factory=list)


# ── ANTIGRAVITY Chat / Memory / Firestore models ──────────────────────────────

class ChatRequest(BaseModel):
    """Request body for POST /chat."""
    user_id: str = Field(..., min_length=1)
    query: str = Field(..., min_length=1)
    domain: str | None = Field(default=None, description="Filter memories by domain (e.g. Python, DSA)")
    topic: str | None = Field(default=None, description="Filter memories by topic (e.g. loops, recursion)")


class MemoryItem(BaseModel):
    """Single user memory entry."""
    memory_id: str
    type: str
    domain: str
    topic: str
    content: str
    distance: float | None = None


class ChatAPIResponse(BaseModel):
    """Response from POST /chat."""
    answer: str
    user_context_used: str
    new_memories: list[MemoryItem] = Field(default_factory=list)
    domain: str | None = None
    topic: str | None = None


class MemoryStoreRequest(BaseModel):
    """Manually store a memory via POST /memory."""
    user_id: str = Field(..., min_length=1)
    domain: str = Field(..., min_length=1)
    topic: str = Field(..., min_length=1)
    type: str = Field(..., pattern="^(weakness|strength|preference)$")
    content: str = Field(..., min_length=5)


class MemoryListResponse(BaseModel):
    """Response from GET /memory/{user_id}."""
    user_id: str
    memories: list[MemoryItem]
    total: int


class FirestoreProfileRequest(BaseModel):
    """Upsert user profile in Firestore."""
    user_id: str = Field(..., min_length=1)
    name: str | None = None
    email: str | None = None


class DomainScoreRequest(BaseModel):
    """Record a quiz/coding score for a domain."""
    user_id: str = Field(..., min_length=1)
    domain: str = Field(..., min_length=1)
    score: float = Field(..., ge=0, le=100)
    total_questions: int = Field(..., ge=1)
    correct: int = Field(..., ge=0)


class TopicCompleteRequest(BaseModel):
    """Mark a topic as completed and award XP."""
    user_id: str = Field(..., min_length=1)
    domain: str = Field(..., min_length=1)
    topic: str = Field(..., min_length=1)
    xp_earned: int = Field(default=10, ge=0)
