export interface QuizQuestion {
  id: string;
  topic: string;
  concept: string; // 🔥 Added: micro-gap tracking
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  promptVisual?: string;
  optionVisuals?: string[];
  cardStyle?: "visual";
  promptImageSrc?: string;
  promptImageAlt?: string;
}

export const QUIZ_DATA: Record<string, QuizQuestion[]> = {
  DSA: [
    {
      id: "dsa-1",
      topic: "Loops",
      concept: "loop iterations",
      question: "What does a `for` loop with `i = 0; i < 5; i++` execute?",
      options: ["5 iterations (0,1,2,3,4)", "4 iterations (1,2,3,4)", "6 iterations (0,1,2,3,4,5)", "Infinite loop"],
      correctIndex: 0,
      explanation: "The loop starts at i=0, runs while i<5, so executes for i = 0,1,2,3,4 — exactly 5 iterations.",
    },
    {
      id: "dsa-2",
      topic: "Loops",
      concept: "break statements",
      question: "How do you break out of a loop early in most languages?",
      options: ["continue", "return", "break", "exit"],
      correctIndex: 2,
      explanation: "`break` immediately terminates the current loop. `continue` skips the rest of the current iteration but doesn't exit the loop.",
    },
    {
      id: "dsa-3",
      topic: "Arrays",
      concept: "array access time",
      question: "What is the time complexity to access an element at index `i` in an array?",
      options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
      correctIndex: 2,
      explanation: "Arrays store elements in contiguous memory. Accessing index i is a single arithmetic operation (base + i × size) — always O(1).",
    },
    {
      id: "dsa-4",
      topic: "Arrays",
      concept: "array indexing",
      question: "Given arr = [3, 1, 4, 1, 5], what is arr[2]?",
      options: ["1", "4", "3", "5"],
      correctIndex: 1,
      explanation: "Arrays are 0-indexed. arr[0]=3, arr[1]=1, arr[2]=4. The answer is 4.",
    },
    {
      id: "dsa-5",
      topic: "Sorting",
      concept: "quicksort complexity",
      question: "What is the average time complexity of QuickSort?",
      options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
      correctIndex: 1,
      explanation: "QuickSort's average case is O(n log n). It partitions the array around a pivot, making ~log n recursive levels each doing O(n) work.",
    },
    {
      id: "dsa-6",
      topic: "Sorting",
      concept: "stable sorting",
      question: "Which sort algorithm is stable and has O(n log n) worst case?",
      options: ["QuickSort", "HeapSort", "MergeSort", "BubbleSort"],
      correctIndex: 2,
      explanation: "MergeSort is stable (preserves order of equal elements) and guarantees O(n log n) in all cases, unlike QuickSort which can degrade to O(n²).",
    },
    {
      id: "dsa-7",
      topic: "Searching",
      concept: "binary search pre-requisite",
      question: "Binary search requires the array to be:",
      options: ["Random", "Sorted", "Reversed", "Empty"],
      correctIndex: 1,
      explanation: "Binary search works by repeatedly halving the search space — this is only possible if the array is sorted.",
    },
    {
      id: "dsa-8",
      topic: "Variables",
      concept: "type coercion",
      question: "What is the result of: `let x = '5' + 3` in JavaScript?",
      options: ["8", "53", "'53'", "Error"],
      correctIndex: 2,
      explanation: "In JavaScript, `+` with a string triggers concatenation. '5' + 3 coerces 3 to '3', giving '53'.",
    },
  ],
  "Web Dev": [
    {
      id: "web-1",
      topic: "HTML Basics",
      concept: "HTML tags",
      question: "Which HTML tag creates a hyperlink?",
      options: ["<link>", "<href>", "<a>", "<url>"],
      correctIndex: 2,
      explanation: "The `<a>` (anchor) tag creates hyperlinks.",
    },
    {
      id: "web-2",
      topic: "CSS Basics",
      concept: "CSS properties",
      question: "Which CSS property controls text size?",
      options: ["text-size", "font-size", "size", "text-scale"],
      correctIndex: 1,
      explanation: "`font-size` sets the size of the font.",
    },
    {
      id: "web-3",
      topic: "JS Basics",
      concept: "strict equality",
      question: "What does `===` check in JavaScript?",
      options: ["Only value equality", "Only type equality", "Value AND type equality", "Reference equality"],
      correctIndex: 2,
      explanation: "`===` checks both value AND type.",
    },
    {
      id: "web-4",
      topic: "DOM",
      concept: "DOM selection",
      question: "How do you select an element with id='btn' in JavaScript?",
      options: ["document.querySelector('.btn')", "document.getElementById('btn')", "document.getElement('btn')", "document.select('#btn')"],
      correctIndex: 1,
      explanation: "`getElementById('btn')` directly targets the element with that ID.",
    },
    {
      id: "web-5",
      topic: "Flexbox",
      concept: "flexbox activation",
      question: "Which CSS property makes elements flex?",
      options: ["display: block", "display: grid", "display: flex", "position: flex"],
      correctIndex: 2,
      explanation: "`display: flex` activates flexbox on the container.",
    },
    {
      id: "web-6",
      topic: "Events",
      concept: "event listeners",
      question: "Which event fires when you click a button?",
      options: ["onhover", "onclick", "onpress", "ontap"],
      correctIndex: 1,
      explanation: "The `click` event fires when a user clicks an element.",
    },
    {
      id: "web-7",
      topic: "React Basics",
      concept: "JSX syntax",
      question: "What is JSX in React?",
      options: ["A database query language", "A syntax extension that looks like HTML in JavaScript", "A CSS preprocessor", "A testing framework"],
      correctIndex: 1,
      explanation: "JSX lets you write HTML-like syntax inside JavaScript.",
    },
    {
      id: "web-8",
      topic: "Fetch/API",
      concept: "async responses",
      question: "What does `fetch()` return in JavaScript?",
      options: ["The response data directly", "A Promise", "A callback", "JSON automatically"],
      correctIndex: 1,
      explanation: "`fetch()` returns a Promise.",
    },
  ],
  Aptitude: [
    {
      id: "apt-1",
      topic: "Arithmetic",
      concept: "percentage calculation",
      question: "What is 15% of 200?",
      options: ["25", "30", "35", "40"],
      correctIndex: 1,
      explanation: "15% of 200 = (15/100) × 200 = 30.",
    },
    {
      id: "apt-2",
      topic: "Percentages",
      concept: "percentage increase",
      question: "A price increases from 80 to 100. What is the % increase?",
      options: ["20%", "25%", "15%", "30%"],
      correctIndex: 1,
      explanation: "% increase = (100-80)/80 × 100 = 25%.",
    },
    {
      id: "apt-3",
      topic: "Ratios",
      concept: "ratio chain",
      question: "If A:B = 2:3 and B:C = 3:4, what is A:C?",
      options: ["1:2", "2:4", "3:4", "2:3"],
      correctIndex: 1,
      explanation: "A/C = A/B × B/C = (2/3) × (3/4) = 1/2.",
    },
    {
      id: "apt-4",
      topic: "Algebra",
      concept: "linear equations",
      question: "If 3x + 6 = 21, what is x?",
      options: ["3", "5", "7", "4"],
      correctIndex: 1,
      explanation: "3x = 15 → x = 5.",
    },
    {
      id: "apt-5",
      topic: "Time & Work",
      concept: "joint work rate",
      question: "A can do a job in 10 days, B in 15 days. Together, how many days?",
      options: ["5", "6", "7", "8"],
      correctIndex: 1,
      explanation: "1/10 + 1/15 = 5/30 = 1/6. Time = 6 days.",
    },
    {
      id: "apt-6",
      topic: "Profit & Loss",
      concept: "profit percentage",
      question: "Buy at ₹100, sell at ₹120. What is the profit %?",
      options: ["10%", "20%", "15%", "25%"],
      correctIndex: 1,
      explanation: "Profit % = (20/100) × 100 = 20%.",
    },
    {
      id: "apt-7",
      topic: "Time & Distance",
      concept: "speed time distance",
      question: "Speed = 60 km/h, Distance = 180 km. Time taken?",
      options: ["2 hours", "3 hours", "4 hours", "2.5 hours"],
      correctIndex: 1,
      explanation: "Time = 180/60 = 3 hours.",
    },
    {
      id: "apt-8",
      topic: "Probability",
      concept: "basic probability",
      question: "A bag has 3 red, 2 blue balls. P(red) = ?",
      options: ["2/5", "3/5", "1/2", "3/2"],
      correctIndex: 1,
      explanation: "Total balls = 5. P(red) = 3/5.",
    },
  ],
  "App Dev": [
    {
      id: "app-1",
      topic: "React Native Basics",
      concept: "hybrid app concept",
      question: "What does React Native primarily let you build?",
      options: ["Only Android games", "Native mobile apps using React concepts", "Only PWAs", "Backend APIs"],
      correctIndex: 1,
      explanation: "React Native lets you build native-feeling mobile apps for iOS and Android.",
    },
    {
      id: "app-2",
      topic: "Navigation & Routing",
      concept: "mobile navigation",
      question: "Why is navigation important in a mobile app?",
      options: ["It changes your app icon", "It controls movement between screens", "It improves battery health", "It replaces state"],
      correctIndex: 1,
      explanation: "Navigation manages how users move from one screen to another.",
    },
    {
      id: "app-3",
      topic: "UI Components",
      concept: "component reusability",
      question: "Why use reusable UI components?",
      options: ["To avoid styling entirely", "To make apps slower", "To keep the UI consistent and easier to maintain", "To remove routing"],
      correctIndex: 2,
      explanation: "Reusable components reduce duplication and visual inconsistency.",
    },
    {
      id: "app-4",
      topic: "State Management",
      concept: "dynamic app state",
      question: "What is state in an app?",
      options: ["The operating system", "Data that changes over time and affects the UI", "A deployment server", "Only API responses"],
      correctIndex: 1,
      explanation: "State is the changing data your UI depends on.",
    },
    {
      id: "app-5",
      topic: "Native APIs",
      concept: "hardware access",
      question: "Which of these is a native API use case?",
      options: ["Reading the camera", "Creating HTML tables", "Compiling CSS", "Running SQL in a browser"],
      correctIndex: 0,
      explanation: "Camera access is a classic native-device capability.",
    },
    {
      id: "app-6",
      topic: "Firebase Integration",
      concept: "BaaS concepts",
      question: "Firebase is commonly used for:",
      options: ["Phone hardware repair", "Auth, database, and backend services", "Compiling Kotlin only", "Designing icons"],
      correctIndex: 1,
      explanation: "Firebase often provides authentication and databases.",
    },
    {
      id: "app-7",
      topic: "App Store Deployment",
      concept: "deployment pre-requisites",
      question: "Before store deployment, you usually need:",
      options: ["No testing", "A stable build and release configuration", "Only a README", "To remove app icons"],
      correctIndex: 1,
      explanation: "Deployment usually needs a production-ready build and signing.",
    },
    {
      id: "app-8",
      topic: "Performance Optimization",
      concept: "efficiency strategies",
      question: "A slow mobile screen is usually improved by:",
      options: ["Rendering more unnecessary items", "Reducing extra work and unnecessary re-renders", "Adding more alerts", "Using larger images everywhere"],
      correctIndex: 1,
      explanation: "Performance work focused on rendering less and doing less work per frame.",
    },
  ],
  "Data Science": [
    {
      id: "ds-1",
      topic: "Python",
      concept: "data processing",
      question: "Which library is most common for tabular data (tables) in Python?",
      options: ["Math", "Pandas", "Request", "Pygame"],
      correctIndex: 1,
      explanation: "Pandas is the standard library for manipulating structured, tabular data.",
    },
    {
      id: "ds-2",
      topic: "Numpy",
      concept: "array operations",
      question: "What is NumPy mainly used for?",
      options: ["Web design", "Fast numerical array operations", "Writing CSS", "Mobile navigation"],
      correctIndex: 1,
      explanation: "NumPy provides high-performance vector and matrix calculations.",
    },
    {
      id: "ds-3",
      topic: "Viz",
      concept: "visualization types",
      question: "A 'Correlation Heatmap' is best for showing:",
      options: ["A list of names", "Relationships between multiple features", "The time of day", "Single value counters"],
      correctIndex: 1,
      explanation: "Heatmaps quickly show how strongly variables relate to one another.",
    },
    {
      id: "ds-4",
      topic: "ML",
      concept: "supervised learning",
      question: "Predicting a house price (a decimal number) is a:",
      options: ["Classification problem", "Regression problem", "Clustering task", "Cleaning step"],
      correctIndex: 1,
      explanation: "Regression predicts continuous numeric values.",
    },
    {
      id: "ds-5",
      topic: "ML",
      concept: "overfitting",
      question: "If a model is perfect on training data but fails on new data, it is likely:",
      options: ["Underfitting", "Overfitting", "Correct", "Too small"],
      correctIndex: 1,
      explanation: "Overfitting happens when a model 'memorizes' noise in training data instead of learning patterns.",
    },
    {
      id: "ds-6",
      topic: "Viz",
      concept: "chart selection",
      question: "Which chart is best for showing a trend over time?",
      options: ["Pie chart", "Bar chart", "Line chart", "Scatter plot"],
      correctIndex: 2,
      explanation: "Line charts naturally show progression and continuity over time.",
    },
    {
      id: "ds-7",
      topic: "Data Cleaning",
      concept: "missing values",
      question: "Wait, my data has 'NaN' everywhere. What does NaN mean?",
      options: ["New and Nice", "Missing or Not-a-Number value", "Now and Next", "Normal and Average"],
      correctIndex: 1,
      explanation: "NaN represents missing or undefined data in datasets.",
    },
    {
      id: "ds-8",
      topic: "Deployment",
      concept: "model serving",
      question: "Why would you 'pickle' a model in Python?",
      options: ["To clean it", "To save the trained model to a file for later use", "To make it faster", "To encrypt it"],
      correctIndex: 1,
      explanation: "Pickling (serialization) saves the model state so you don't have to retrain it every time.",
    },
  ],
  Cybersecurity: [
    {
      id: "cyber-1",
      topic: "Networking",
      concept: "IP addressing",
      question: "What does an IP address uniquely identify?",
      options: ["A user's name", "A device on a network", "A website's CSS", "The type of monitor"],
      correctIndex: 1,
      explanation: "IP addresses are the 'digital home addresses' for devices on a network.",
    },
    {
      id: "cyber-2",
      topic: "Linux",
      concept: "root access",
      question: "What does the 'sudo' command do?",
      options: ["Deletes a file", "Runs a command with admin (root) privileges", "Restarts the PC", "Prints a greeting"],
      correctIndex: 1,
      explanation: "Sudo stands for 'SuperUser Do' and allows restricted system operations.",
    },
    {
      id: "cyber-3",
      topic: "OWASP",
      concept: "SQL injection",
      question: "SQL Injection is a vulnerability that occurs in:",
      options: ["CSS files", "Database queries using user input", "Image metadata", "Keyboard drivers"],
      correctIndex: 1,
      explanation: "SQLi happens when an attacker inserts malicious code into a database query via user inputs.",
    },
    {
      id: "cyber-4",
      topic: "Nmap",
      concept: "port scanning",
      question: "What is the primary purpose of Nmap?",
      options: ["Editing videos", "Scanning a network for open ports and services", "Checking email", "Designing logos"],
      correctIndex: 1,
      explanation: "Nmap is the industry standard for network discovery and security auditing.",
    },
    {
      id: "cyber-5",
      topic: "Phishing",
      concept: "social engineering",
      question: "A fake email asking for your password is an example of:",
      options: ["Brute force", "Phishing", "DDoS", "Ransomware"],
      correctIndex: 1,
      explanation: "Phishing uses deception (social engineering) to trick users into giving up secrets.",
    },
    {
      id: "cyber-6",
      topic: "Encryption",
      concept: "hashing",
      question: "Why should you store passwords as 'hashes' and not plain text?",
      options: ["To make them faster", "So that even if stolen, the real password isn't visible", "To confuse the user", "Because hashes take less space"],
      correctIndex: 1,
      explanation: "Hashing is a one-way transformation that secures sensitive data like passwords.",
    },
    {
      id: "cyber-7",
      topic: "CTF",
      concept: "capture the flag",
      question: "In Cybersecurity, what is a 'Flag'?",
      options: ["A literal cloth flag", "A hidden secret string proving you solved a challenge", "A country's symbol", "A type of firewall"],
      correctIndex: 1,
      explanation: "CTF (Capture The Flag) competitions use 'flags' as proof of compromise or success.",
    },
    {
      id: "cyber-8",
      topic: "Firewalls",
      concept: "traffic filtering",
      question: "What does a firewall do?",
      options: ["Speeds up internet", "Blocks or allows network traffic based on rules", "Cleans the hard drive", "Hosts a website"],
      correctIndex: 1,
      explanation: "Firewalls act as security guards for incoming and outgoing network traffic.",
    },
  ],
  IoT: [
    {
      id: "iot-1",
      topic: "Arduino",
      concept: "microcontroller basics",
      question: "What is an Arduino?",
      options: ["A high-end PC", "An open-source microcontroller board", "A type of sensor", "A coding language"],
      correctIndex: 1,
      explanation: "Arduino is a popular hardware platform for building electronics projects.",
    },
    {
      id: "iot-2",
      topic: "Sensors",
      concept: "sensor types",
      question: "Which sensor would you use to measure room temperature?",
      options: ["LDR (Light sensor)", "Ultrasonic sensor", "DHT11 / Thermistor", "Potentiometer"],
      correctIndex: 2,
      explanation: "DHT11 and thermistors are common for measuring environmental heat.",
    },
    {
      id: "iot-3",
      topic: "Protocols",
      concept: "MQTT lightweight",
      question: "Why is MQTT preferred for tiny IoT devices?",
      options: ["It is very fast", "It is extremely lightweight and low-bandwidth", "It supports video streaming", "It only works on Windows"],
      correctIndex: 1,
      explanation: "MQTT is designed for remote connections where bandwidth and power are limited.",
    },
    {
      id: "iot-4",
      topic: "Edge",
      concept: "edge computing",
      question: "What is 'Edge Computing' in IoT?",
      options: ["Processing data on the device itself instead of just the cloud", "Living on the edge of a city", "Using 5G only", "Web design"],
      correctIndex: 0,
      explanation: "Edge computing reduces latency by processing data locally at the source (the device).",
    },
    {
      id: "iot-5",
      topic: "GPIO",
      concept: "pin control",
      question: "What does GPIO stand for?",
      options: ["Global Process Input Output", "General Purpose Input Output", "Ground Position In Out", "General Power In Out"],
      correctIndex: 1,
      explanation: "GPIO pins are the standard way microcontrollers talk to external hardware (LEDs, sensors, etc).",
    },
    {
      id: "iot-6",
      topic: "Power",
      concept: "sleep modes",
      question: "How do battery-powered IoT devices last for years?",
      options: ["Buying big batteries", "Using 'Deep Sleep' modes when not active", "Connecting to Wi-Fi 24/7", "Having no sensors"],
      correctIndex: 1,
      explanation: "Sleep modes significantly reduce power consumption when the device isn't doing work.",
    },
    {
      id: "iot-7",
      topic: "Connectivity",
      concept: "LoRaWAN range",
      question: "Which technology is best for long-range (kilometers) low-power IoT?",
      options: ["Bluetooth", "Wi-Fi", "LoRaWAN", "NFC"],
      correctIndex: 2,
      explanation: "LoRaWAN (Long Range Wide Area Network) is designed for range and low battery usage.",
    },
    {
      id: "iot-8",
      topic: "Security",
      concept: "default credentials",
      question: "A common mistake in IoT security is:",
      options: ["Using strong passwords", "Keeping default 'admin' passwords", "Updating firmware", "Encrypting data"],
      correctIndex: 1,
      explanation: "Many IoT hacks happen because devices ship with weak, default passwords that are never changed.",
    },
  ],
  Python: [
    {
      id: "py-1",
      topic: "Syntax",
      concept: "indentation",
      question: "How does Python define blocks of code (like inside an 'if' statements)?",
      options: ["Curly braces {}", "Semicolons ;", "Indentation (spaces)", "Parentheses ()"],
      correctIndex: 2,
      explanation: "Python is unique because it uses white space (indentation) to structure code blocks.",
    },
    {
      id: "py-2",
      topic: "Data Types",
      concept: "list vs tuple",
      question: "Which of these can be changed (muted) after creation?",
      options: ["Tuple", "String", "List", "Integer"],
      correctIndex: 2,
      explanation: "Lists are mutable (changeable). Tuples and Strings are immutable.",
    },
    {
      id: "py-3",
      topic: "Functions",
      concept: "keyword arguments",
      question: "What does `def my_func(a, b=5):` mean for 'b'?",
      options: ["b must be 5", "b is a required string", "b has a default value of 5 if not provided", "b is multiplied by 5"],
      correctIndex: 2,
      explanation: "Parameters can have default values, making them optional when calling the function.",
    },
    {
      id: "py-4",
      topic: "OOP",
      concept: "class init",
      question: "Which method is the constructor in a Python class?",
      options: ["__start__", "__main__", "__init__", "__set__"],
      correctIndex: 2,
      explanation: "`__init__` is called automatically when a new object of a class is created.",
    },
    {
      id: "py-5",
      topic: "Modules",
      concept: "importing",
      question: "How do you use a library called 'math' in your code?",
      options: ["get math", "import math", "use math", "require math"],
      correctIndex: 1,
      explanation: "The `import` keyword brings modular code from libraries into your script.",
    },
    {
      id: "py-6",
      topic: "Dictionaries",
      concept: "key-value access",
      question: "How do you access the value of 'name' in `d = {'name': 'Alice'}`?",
      options: ["d[0]", "d.name", "d['name']", "d.get(0)"],
      correctIndex: 2,
      explanation: "Dictionaries are accessed via their keys inside square brackets or using `.get()`.",
    },
    {
      id: "py-7",
      topic: "Libraries",
      concept: "package manager",
      question: "What tool is used to install Python packages from the internet?",
      options: ["npm", "apt", "pip", "brew"],
      correctIndex: 2,
      explanation: "Pip is the standard package installer for Python.",
    },
    {
      id: "py-8",
      topic: "Debugging",
      concept: "print vs debug",
      question: "What is the quickest way to see the value of a variable during execution?",
      options: ["Reading the code", "Using `print()`", "Writing a comment", "Restarting the PC"],
      correctIndex: 1,
      explanation: "`print()` is the most common technique for quick logging and debugging.",
    },
  ],
  "Product Design": [
    {
      id: "design-1",
      topic: "UI/UX",
      concept: "UX vs UI",
      question: "What is the primary focus of User Experience (UX)?",
      options: ["Picking colors", "How a user feels and interacts with a system", "Writing code", "Database architecture"],
      correctIndex: 1,
      explanation: "UX is about the overall journey and usability, while UI focuses on the visual look.",
    },
    {
      id: "design-2",
      topic: "Figma",
      concept: "components",
      question: "In Figma, a 'Component' is used to:",
      options: ["Delete layers", "Create reusable elements that update everywhere", "Export CSS only", "Record videos"],
      correctIndex: 1,
      explanation: "Components let you reuse design elements like buttons consistently across your project.",
    },
    {
      id: "design-3",
      topic: "Color Theory",
      concept: "contrast",
      question: "Why is high contrast important in UI design?",
      options: ["It looks trendy", "Accessibility (making it readable for everyone)", "It saves battery", "It makes images larger"],
      correctIndex: 1,
      explanation: "High contrast ensures text is readable for users with visual impairments or in tricky lighting.",
    },
    {
      id: "design-4",
      topic: "Prototyping",
      concept: "interactivity",
      question: "A prototype is different from a static design because it is:",
      options: ["Interactive and clickable", "Bigger in size", "Blue colored", "Written in React"],
      correctIndex: 0,
      explanation: "Prototypes simulate the final product's flow and interaction.",
    },
    {
      id: "design-5",
      topic: "Typography",
      concept: "hierarchy",
      question: "Visual hierarchy in typography is achieved by:",
      options: ["Using only one font size", "Varying font sizes, weights, and colors", "Hiding text", "Underlining everything"],
      correctIndex: 1,
      explanation: "Hierarchy guides the user's eye to the most important info first.",
    },
    {
      id: "design-6",
      topic: "User Research",
      concept: "personas",
      question: "What is a 'User Persona'?",
      options: ["A real person", "A fictional profile representing a target user group", "An AI bot", "A marketing logo"],
      correctIndex: 1,
      explanation: "Personas help designers keep the user's goals and frustrations in mind.",
    },
    {
      id: "design-7",
      topic: "Layout",
      concept: "white space",
      question: "What is 'White Space' (Negative Space)?",
      options: ["Wasted space", "The empty space between elements to improve focus", "Background color only", "A bug in the layout"],
      correctIndex: 1,
      explanation: "White space reduces cognitive load and makes a layout feel organized.",
    },
    {
      id: "design-8",
      topic: "Heuristics",
      concept: "user control",
      question: "A 'Cancel' button or 'Undo' feature relates to which principle?",
      options: ["Visual flair", "User control and freedom", "System speed", "Data storage"],
      correctIndex: 1,
      explanation: "Users need 'emergency exits' when they make mistakes or change their minds.",
    },
  ],
  Marketing: [
    {
      id: "mkt-1",
      topic: "Digital Marketing",
      concept: "SEO basics",
      question: "What does SEO stand for?",
      options: ["Social Enterprise Office", "Search Engine Optimization", "Static Entry Object", "Sales Efficiency Option"],
      correctIndex: 1,
      explanation: "SEO is the practice of improving a website to increase its visibility in search engines.",
    },
    {
      id: "mkt-2",
      topic: "Content",
      concept: "CTA importance",
      question: "What is a 'Call to Action' (CTA)?",
      options: ["A long paragraph", "A prompt that tells the user what to do next (e.g. 'Buy Now')", "A customer support call", "A marketing budget"],
      correctIndex: 1,
      explanation: "CTAs drive conversions by giving users a clear next step.",
    },
    {
      id: "mkt-3",
      topic: "SEM",
      concept: "PPC vs Organic",
      question: "Pay-Per-Click (PPC) means you pay when:",
      options: ["Someone sees your ad", "Someone clicks your ad", "The month ends", "You sell a product"],
      correctIndex: 1,
      explanation: "PPC is an advertising model where you only pay for actual user engagement (clicks).",
    },
    {
      id: "mkt-4",
      topic: "Analytics",
      concept: "bounce rate",
      question: "What does 'Bounce Rate' measure?",
      options: ["How fast a site loads", "Users who leave after viewing only one page", "The number of purchases", "Server errors"],
      correctIndex: 1,
      explanation: "A high bounce rate indicates that users aren't finding what they need or the UX is poor.",
    },
    {
      id: "mkt-5",
      topic: "Social Media",
      concept: "engagement metrics",
      question: "Which of these is an 'Engagement' metric?",
      options: ["Total reach", "Comments and Shares", "Ad spend", "Font size"],
      correctIndex: 1,
      explanation: "Engagements show how much people are actually interacting with your content.",
    },
    {
      id: "mkt-6",
      topic: "Email Marketing",
      concept: "segmentation",
      question: "Why segment an email list?",
      options: ["To delete contacts", "To send relevant content to specific groups of people", "To make the list shorter", "To bypass spam filters only"],
      correctIndex: 1,
      explanation: "Segmentation increases conversion by matching the right message to the right audience.",
    },
    {
      id: "mkt-7",
      topic: "Branding",
      concept: "brand voice",
      question: "What is 'Brand Voice'?",
      options: ["The sound of an ad", "The consistent personality and emotion in communications", "A brand's theme song", "The CEO's voice"],
      correctIndex: 1,
      explanation: "Brand voice makes a company feel human and recognizable across all platforms.",
    },
    {
      id: "mkt-8",
      topic: "Funnel",
      concept: "conversion funnel",
      question: "The bottom of the marketing funnel usually targets:",
      options: ["Brand awareness", "Driving a final sale/conversion", "Education", "Initial research"],
      correctIndex: 1,
      explanation: "The bottom-of-funnel (BOFU) is where you turn 'leads' into 'customers'.",
    },
  ],
  Business: [
    {
      id: "biz-1",
      topic: "Finance",
      concept: "revenue vs profit",
      question: "Profit is calculated as:",
      options: ["Total Revenue", "Revenue minus Expenses", "Revenue plus Loans", "Cash in bank"],
      correctIndex: 1,
      explanation: "Profit is the 'bottom line'—the money left over after all costs are paid.",
    },
    {
      id: "biz-2",
      topic: "Startup",
      concept: "MVP",
      question: "What is a 'Minimum Viable Product' (MVP)?",
      options: ["The final polished version", "A version with just enough features to satisfy early customers", "A prototype that doesn't work", "A cheap copy"],
      correctIndex: 1,
      explanation: "An MVP helps you test a business idea with real users as quickly as possible.",
    },
    {
      id: "biz-3",
      topic: "Strategy",
      concept: "SWOT analysis",
      question: "SWOT stands for Strengths, Weaknesses, Opportunities, and:",
      options: ["Tasks", "Threats", "Time", "Trends"],
      correctIndex: 1,
      explanation: "SWOT is a strategic planning tool for competitor and internal analysis.",
    },
    {
      id: "biz-4",
      topic: "Management",
      concept: "KPIs",
      question: "Key Performance Indicators (KPIs) are used to:",
      options: ["Lock the office", "Measure success against specific goals", "Pay taxes", "Hire interns"],
      correctIndex: 1,
      explanation: "KPIs provide quantifiable metrics to track progress over time.",
    },
    {
      id: "biz-5",
      topic: "Growth",
      concept: "churn rate",
      question: "Churn Rate is the percentage of:",
      options: ["New customers", "Customers who stop using your service", "Employees hired", "Profits made"],
      correctIndex: 1,
      explanation: "Reducing churn is vital for long-term growth and sustainability.",
    },
    {
      id: "biz-6",
      topic: "Finance",
      concept: "burn rate",
      question: "What is a startup's 'Burn Rate'?",
      options: ["How fast they spend capital before becoming profitable", "The speed of the office fire drill", "Temperature of the servers", "Total annual revenue"],
      correctIndex: 0,
      explanation: "Burn rate tells you how long a startup can survive before needing more funding.",
    },
    {
      id: "biz-7",
      topic: "Strategy",
      concept: "market fit",
      question: "Product-Market Fit happens when:",
      options: ["You have an idea", "A large market is actually buying and using your product", "You hire a CEO", "You spend a lot on ads"],
      correctIndex: 1,
      explanation: "PMF is the 'holy grail' where demand for your product is clear and consistent.",
    },
    {
      id: "biz-8",
      topic: "Entrepreneurship",
      concept: "equity",
      question: "What is 'Equity' in a business?",
      options: ["A loan", "Ownership interest in the company", "Office furniture", "Debt"],
      correctIndex: 1,
      explanation: "Equity represents how much of the company is owned by founders, employees, or investors.",
    },
  ],
  "Content Creation": [
    {
      id: "create-1",
      topic: "Storytelling",
      concept: "the hook",
      question: "Why is 'The Hook' critical in a video or post?",
      options: ["To finish the video", "To grab attention in the first few seconds", "To show the credits", "To explain the budget"],
      correctIndex: 1,
      explanation: "Viewer retention drops off fast; you must give people a reason to stay immediately.",
    },
    {
      id: "create-2",
      topic: "YouTube",
      concept: "CTR",
      question: "Click-Through Rate (CTR) on YouTube depends mostly on:",
      options: ["The video length", "Thumbnail and Title", "The camera quality", "Background music"],
      correctIndex: 1,
      explanation: "Thumbnails and titles are the 'billboards' that convince people to click.",
    },
    {
      id: "create-3",
      topic: "Video",
      concept: "lighting",
      question: "What is 'Key Light' in a 3-point lighting setup?",
      options: ["A light for the keys", "The primary and strongest light source on the subject", "A background light", "The natural sunlight only"],
      correctIndex: 1,
      explanation: "The key light defines the main look and shadow of your subject.",
    },
    {
      id: "create-4",
      topic: "Audio",
      concept: "audio quality",
      question: "Most viewers will tolerate bad video, but they will leave if:",
      options: ["The music is too quiet", "The audio is bad or distorted", "The font is small", "The thumbnail is blue"],
      correctIndex: 1,
      explanation: "Clear audio is more important for retention than high-resolution video.",
    },
    {
      id: "create-5",
      topic: "Branding",
      concept: "consistency",
      question: "Consistent posting (the 'schedule') helps because:",
      options: ["It makes you tired", "It builds trust and trains the algorithm", "You use more storage", "The camera likes it"],
      correctIndex: 1,
      explanation: "Regularity builds a habit for your audience and provides data for algorithms.",
    },
    {
      id: "create-6",
      topic: "Creative",
      concept: "b-roll",
      question: "What is 'B-Roll' in video editing?",
      options: ["The main footage", "Supplemental footage shown while the main story is narrated", "The bloopers", "The end screen"],
      correctIndex: 1,
      explanation: "B-roll adds visual interest and hides cuts in the main 'A-roll'.",
    },
    {
      id: "create-7",
      topic: "Algorithm",
      concept: "retention",
      question: "Retention in an algorithm means:",
      options: ["How long people stay watching your content", "How many views you have", "How many subscribers you have", "Your video resolution"],
      correctIndex: 0,
      explanation: "Algorithms promote content that keeps users on the platform.",
    },
    {
      id: "create-8",
      topic: "Creative",
      concept: "scripting",
      question: "A 'Story Arc' helps a video by:",
      options: ["Making it longer", "Creating a beginning, a climax, and a resolution", "Recording sounds", "Adding text effects"],
      correctIndex: 1,
      explanation: "Structure keeps viewers emotionally engaged with the content.",
    },
  ],
  "Alphabets (Kindergarten)": [
    {
      id: "alpha-1",
      topic: "Alphabets",
      concept: "letter recognition",
      question: "Tap the letter that starts the alphabet.",
      options: ["B", "Z", "A", "M"],
      correctIndex: 2,
      explanation: "The alphabet starts with A. A is for Apple.",
      promptImageSrc: "/kids/alphabet/alphabet-start.svg",
      promptImageAlt: "Alphabet path starting with the letter A",
      optionVisuals: ["B", "Z", "A", "M"],
      cardStyle: "visual",
    },
    {
      id: "alpha-2",
      topic: "Alphabets",
      concept: "phonics",
      question: "Which letter makes the sound for apple?",
      options: ["A", "R", "P", "S"],
      correctIndex: 0,
      explanation: "Apple begins with the letter A.",
      promptImageSrc: "/kids/alphabet/apple-card.svg",
      promptImageAlt: "A bright red apple",
      optionVisuals: ["A", "R", "P", "S"],
      cardStyle: "visual",
    },
    {
      id: "alpha-3",
      topic: "Alphabets",
      concept: "matching",
      question: "Tap the same letter as the one in the star.",
      options: ["C", "D", "G", "O"],
      correctIndex: 0,
      explanation: "The shining star is showing the letter C.",
      promptImageSrc: "/kids/alphabet/star-c-card.svg",
      promptImageAlt: "A golden star with the letter C",
      optionVisuals: ["C", "D", "G", "O"],
      cardStyle: "visual",
    },
    {
      id: "alpha-4",
      topic: "Alphabets",
      concept: "uppercase recognition",
      question: "Which big letter is H?",
      options: ["H", "N", "A", "E"],
      correctIndex: 0,
      explanation: "That tall standing letter is H.",
      promptImageSrc: "/kids/alphabet/house-h-card.svg",
      promptImageAlt: "A house with the letter H",
      optionVisuals: ["H", "N", "A", "E"],
      cardStyle: "visual",
    },
    {
      id: "alpha-5",
      topic: "Alphabets",
      concept: "word beginning",
      question: "Which letter starts ball?",
      options: ["B", "L", "T", "D"],
      correctIndex: 0,
      explanation: "Ball starts with B.",
      promptImageSrc: "/kids/alphabet/ball-card.svg",
      promptImageAlt: "A colorful ball",
      optionVisuals: ["B", "L", "T", "D"],
      cardStyle: "visual",
    },
  ],
  Alphabets: [
    {
      id: "alpha-k-alias-1",
      topic: "Alphabets",
      concept: "letter recognition",
      question: "Tap the letter that starts the alphabet.",
      options: ["B", "Z", "A", "M"],
      correctIndex: 2,
      explanation: "The alphabet starts with A. A is for Apple.",
      promptImageSrc: "/kids/alphabet/alphabet-start.svg",
      promptImageAlt: "Alphabet path starting with the letter A",
      optionVisuals: ["B", "Z", "A", "M"],
      cardStyle: "visual",
    },
    {
      id: "alpha-k-alias-2",
      topic: "Alphabets",
      concept: "phonics",
      question: "Which letter makes the sound for apple?",
      options: ["A", "R", "P", "S"],
      correctIndex: 0,
      explanation: "Apple begins with the letter A.",
      promptImageSrc: "/kids/alphabet/apple-card.svg",
      promptImageAlt: "A bright red apple",
      optionVisuals: ["A", "R", "P", "S"],
      cardStyle: "visual",
    },
    {
      id: "alpha-k-alias-3",
      topic: "Alphabets",
      concept: "matching",
      question: "Tap the same letter as the one in the star.",
      options: ["C", "D", "G", "O"],
      correctIndex: 0,
      explanation: "The shining star is showing the letter C.",
      promptImageSrc: "/kids/alphabet/star-c-card.svg",
      promptImageAlt: "A golden star with the letter C",
      optionVisuals: ["C", "D", "G", "O"],
      cardStyle: "visual",
    },
    {
      id: "alpha-k-alias-4",
      topic: "Alphabets",
      concept: "uppercase recognition",
      question: "Which big letter is H?",
      options: ["H", "N", "A", "E"],
      correctIndex: 0,
      explanation: "That tall standing letter is H.",
      promptImageSrc: "/kids/alphabet/house-h-card.svg",
      promptImageAlt: "A house with the letter H",
      optionVisuals: ["H", "N", "A", "E"],
      cardStyle: "visual",
    },
    {
      id: "alpha-k-alias-5",
      topic: "Alphabets",
      concept: "word beginning",
      question: "Which letter starts ball?",
      options: ["B", "L", "T", "D"],
      correctIndex: 0,
      explanation: "Ball starts with B.",
      promptImageSrc: "/kids/alphabet/ball-card.svg",
      promptImageAlt: "A colorful ball",
      optionVisuals: ["B", "L", "T", "D"],
      cardStyle: "visual",
    },
  ],
  Numbers: [
    {
      id: "num-1",
      topic: "Numbers",
      concept: "counting",
      question: "How many apples do you see?",
      options: ["2", "3", "4", "5"],
      correctIndex: 1,
      explanation: "There are 3 apples to count.",
      promptVisual: "🍎 🍎 🍎",
      optionVisuals: ["2️⃣", "3️⃣", "4️⃣", "5️⃣"],
      cardStyle: "visual",
    },
    {
      id: "num-2",
      topic: "Numbers",
      concept: "number recognition",
      question: "Tap the number eight.",
      options: ["6", "8", "3", "9"],
      correctIndex: 1,
      explanation: "This round shape number is 8.",
      promptVisual: "🎈 8",
      optionVisuals: ["6️⃣", "8️⃣", "3️⃣", "9️⃣"],
      cardStyle: "visual",
    },
    {
      id: "num-3",
      topic: "Numbers",
      concept: "addition",
      question: "What is 2 stars plus 1 star?",
      options: ["2", "3", "4", "5"],
      correctIndex: 1,
      explanation: "2 plus 1 makes 3.",
      promptVisual: "⭐ ⭐   +   ⭐",
      optionVisuals: ["2️⃣", "3️⃣", "4️⃣", "5️⃣"],
      cardStyle: "visual",
    },
    {
      id: "num-4",
      topic: "Numbers",
      concept: "comparison",
      question: "Which number is bigger?",
      options: ["4", "7", "2", "1"],
      correctIndex: 1,
      explanation: "7 is bigger than 4, 2, and 1.",
      promptVisual: "🐘",
      optionVisuals: ["4️⃣", "7️⃣", "2️⃣", "1️⃣"],
      cardStyle: "visual",
    },
    {
      id: "num-5",
      topic: "Numbers",
      concept: "patterns",
      question: "What comes next: 1, 2, 3, ?",
      options: ["4", "5", "6", "7"],
      correctIndex: 0,
      explanation: "After 3 comes 4.",
      promptVisual: "🚂 1 - 2 - 3",
      optionVisuals: ["4️⃣", "5️⃣", "6️⃣", "7️⃣"],
      cardStyle: "visual",
    },
  ],
  "Colors & Shapes": [
    {
      id: "color-1",
      topic: "Colors",
      concept: "color recognition",
      question: "Tap the yellow color.",
      options: ["Red", "Blue", "Yellow", "Green"],
      correctIndex: 2,
      explanation: "Yellow looks bright like the sun.",
      promptVisual: "☀️",
      optionVisuals: ["🔴", "🔵", "🟡", "🟢"],
      cardStyle: "visual",
    },
    {
      id: "color-2",
      topic: "Shapes",
      concept: "shape recognition",
      question: "Which one is a circle?",
      options: ["Circle", "Square", "Triangle", "Rectangle"],
      correctIndex: 0,
      explanation: "A circle is round all the way around.",
      promptVisual: "🫧",
      optionVisuals: ["⚪", "🟦", "🔺", "▭"],
      cardStyle: "visual",
    },
    {
      id: "color-3",
      topic: "Shapes",
      concept: "shape matching",
      question: "Tap the triangle.",
      options: ["Triangle", "Circle", "Heart", "Square"],
      correctIndex: 0,
      explanation: "A triangle has 3 corners.",
      promptVisual: "⛰️",
      optionVisuals: ["🔺", "⚪", "❤️", "🟦"],
      cardStyle: "visual",
    },
    {
      id: "color-4",
      topic: "Colors",
      concept: "object color",
      question: "What color is a leaf?",
      options: ["Green", "Pink", "Black", "Orange"],
      correctIndex: 0,
      explanation: "Leaves are usually green.",
      promptVisual: "🍃",
      optionVisuals: ["🟢", "🩷", "⚫", "🟠"],
      cardStyle: "visual",
    },
    {
      id: "color-5",
      topic: "Shapes",
      concept: "sorting",
      question: "Which shape has 4 equal sides?",
      options: ["Square", "Circle", "Triangle", "Star"],
      correctIndex: 0,
      explanation: "A square has 4 equal sides.",
      promptVisual: "🧱",
      optionVisuals: ["🟦", "⚪", "🔺", "⭐"],
      cardStyle: "visual",
    },
  ],
  "Rhymes & Stories": [
    {
      id: "rhyme-1",
      topic: "Rhymes",
      concept: "animal recognition",
      question: "Which animal says meow?",
      options: ["Cat", "Dog", "Cow", "Duck"],
      correctIndex: 0,
      explanation: "Cats say meow.",
      promptVisual: "🎵 Meow, meow!",
      optionVisuals: ["🐱", "🐶", "🐮", "🦆"],
      cardStyle: "visual",
    },
    {
      id: "rhyme-2",
      topic: "Stories",
      concept: "story sequencing",
      question: "What do we do first before sleeping?",
      options: ["Brush teeth", "Play football", "Eat ice cream", "Jump loudly"],
      correctIndex: 0,
      explanation: "We brush our teeth before bedtime.",
      promptVisual: "🌙 🛏️",
      optionVisuals: ["🪥", "⚽", "🍦", "🤸"],
      cardStyle: "visual",
    },
    {
      id: "rhyme-3",
      topic: "Rhymes",
      concept: "rhyme pair",
      question: "Which word sounds like cat?",
      options: ["Hat", "Sun", "Tree", "Dog"],
      correctIndex: 0,
      explanation: "Cat and hat rhyme together.",
      promptVisual: "🐱 + ?",
      optionVisuals: ["🎩", "☀️", "🌳", "🐶"],
      cardStyle: "visual",
    },
    {
      id: "rhyme-4",
      topic: "Stories",
      concept: "emotion recognition",
      question: "Which face looks happy?",
      options: ["Happy", "Sleepy", "Sad", "Angry"],
      correctIndex: 0,
      explanation: "A happy face has a smile.",
      promptVisual: "😊",
      optionVisuals: ["😄", "😴", "😢", "😠"],
      cardStyle: "visual",
    },
    {
      id: "rhyme-5",
      topic: "Stories",
      concept: "listening comprehension",
      question: "Who shines in the night sky?",
      options: ["Moon", "Chair", "Fish", "Bus"],
      correctIndex: 0,
      explanation: "The moon shines at night.",
      promptVisual: "🌌",
      optionVisuals: ["🌙", "🪑", "🐟", "🚌"],
      cardStyle: "visual",
    },
  ],
  "Nature & EVS": [
    {
      id: "nature-1",
      topic: "Animals",
      concept: "animal habitat",
      question: "Which animal lives in water?",
      options: ["Fish", "Lion", "Cow", "Monkey"],
      correctIndex: 0,
      explanation: "Fish live in water.",
      promptVisual: "🌊",
      optionVisuals: ["🐟", "🦁", "🐄", "🐒"],
      cardStyle: "visual",
    },
    {
      id: "nature-2",
      topic: "Plants",
      concept: "plant needs",
      question: "What do plants need to grow?",
      options: ["Water", "Shoes", "Television", "Pillow"],
      correctIndex: 0,
      explanation: "Plants need water to grow.",
      promptVisual: "🪴",
      optionVisuals: ["💧", "👟", "📺", "🛏️"],
      cardStyle: "visual",
    },
    {
      id: "nature-3",
      topic: "Weather",
      concept: "weather recognition",
      question: "What falls from the sky on a rainy day?",
      options: ["Rain", "Books", "Sand", "Pencils"],
      correctIndex: 0,
      explanation: "Rain falls from the clouds.",
      promptVisual: "☁️",
      optionVisuals: ["🌧️", "📚", "🏖️", "✏️"],
      cardStyle: "visual",
    },
    {
      id: "nature-4",
      topic: "Body",
      concept: "body parts",
      question: "Which body part helps you see?",
      options: ["Eyes", "Feet", "Hands", "Ears"],
      correctIndex: 0,
      explanation: "We use our eyes to see.",
      promptVisual: "👀",
      optionVisuals: ["👁️", "🦶", "✋", "👂"],
      cardStyle: "visual",
    },
    {
      id: "nature-5",
      topic: "Hygiene",
      concept: "healthy habits",
      question: "What should you do before eating?",
      options: ["Wash hands", "Throw toys", "Sleep", "Run outside"],
      correctIndex: 0,
      explanation: "Clean hands help keep us healthy.",
      promptVisual: "🫧",
      optionVisuals: ["🧼", "🧸", "😴", "🏃"],
      cardStyle: "visual",
    },
  ],
  "Physics (11th Grade - Science)": [
    {
      id: "physics-11-1",
      topic: "Mechanics",
      concept: "vector addition",
      question: "Which of these is a scalar quantity?",
      options: ["Force", "Velocity", "Distance", "Displacement"],
      correctIndex: 2,
      explanation: "Distance has only magnitude, making it scalar. Displacement and force have both magnitude and direction (vector).",
    },
    {
      id: "physics-11-2",
      topic: "Dynamics",
      concept: "Newton's 2nd Law",
      question: "F = ma. If mass is doubled with the same force, what happens to acceleration?",
      options: ["Doubles", "Halves", "Stays same", "Quadruples"],
      correctIndex: 1,
      explanation: "Acceleration is inversely proportional to mass (a = F/m). Doubling mass cuts acceleration in half.",
    },
  ],
  "Chemistry (11th Grade - Science)": [
    {
      id: "chem-11-1",
      topic: "Atomic Structure",
      concept: "quantum numbers",
      question: "What is the maximum number of electrons in an 's' orbital?",
      options: ["2", "6", "10", "14"],
      correctIndex: 0,
      explanation: "An 's' orbital can hold a maximum of 2 electrons with opposite spins.",
    },
    {
      id: "chem-11-2",
      topic: "Periodicity",
      concept: "electronegativity",
      question: "Which is the most electronegative element?",
      options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"],
      correctIndex: 2,
      explanation: "Fluorine is the most electronegative element on the periodic table.",
    },
  ],
  "Mathematics (11th Grade - Science)": [
    {
      id: "math-11-1",
      topic: "Sets",
      concept: "null set",
      question: "What is the number of elements in a Null Set?",
      options: ["1", "0", "Infinite", "Undefined"],
      correctIndex: 1,
      explanation: "A null set (void set) by definition has zero elements.",
    },
    {
      id: "math-11-2",
      topic: "Trigonometry",
      concept: "basic identities",
      question: "sin²θ + cos²θ = ?",
      options: ["0", "1", "tan²θ", "2"],
      correctIndex: 1,
      explanation: "This is the fundamental Pythagorean identity of trigonometry.",
    },
  ],
  "Biology (11th Grade - Science)": [
    {
      id: "bio-11-1",
      topic: "Cell Biology",
      concept: "mitosis phases",
      question: "In which phase of mitosis do chromosomes align at the center?",
      options: ["Prophase", "Metaphase", "Anaphase", "Telophase"],
      correctIndex: 1,
      explanation: "Metaphase is the stage where chromosomes line up along the equatorial plate.",
    },
  ],
  "Accountancy (11th Grade - Commerce)": [
    {
      id: "acc-11-1",
      topic: "Basic Terms",
      concept: "accounting equation",
      question: "Assets = Liabilities + ?",
      options: ["Capital", "Revenue", "Expense", "Inventory"],
      correctIndex: 0,
      explanation: "The accounting equation states that Total Assets must equal total Liabilities plus Owner's Capital.",
    },
  ],
  "Economics (11th Grade - Commerce)": [
    {
      id: "eco-11-1",
      topic: "Microeconomics",
      concept: "scarcity",
      question: "The central problem of an economy is:",
      options: ["Overproduction", "Scarcity of resources", "Too much money", "High exports"],
      correctIndex: 1,
      explanation: "Economics is the study of how society manages its scarce resources to meet unlimited wants.",
    },
  ],
  "Medical / MBBS / BDS": [
    {
      id: "med-1",
      topic: "Anatomy",
      concept: "human skeleton",
      question: "What is the smallest bone in the human body?",
      options: ["Femur", "Stapes", "Humerus", "Tibia"],
      correctIndex: 1,
      explanation: "The stapes, located in the middle ear, is the smallest and lightest bone.",
    },
    {
      id: "med-2",
      topic: "Physiology",
      concept: "blood circulation",
      question: "Which organ pumps oxygenated blood and deoxygenated blood separately?",
      options: ["Lung", "Heart", "Liver", "Kidney"],
      correctIndex: 1,
      explanation: "The human heart uses a double circulation system to keep oxygenated and deoxygenated blood apart.",
    },
  ],
  "Law / LLB": [
    {
      id: "law-1",
      topic: "Constitutional Law",
      concept: "fundamental rights",
      question: "Which article of the Indian Constitution deals with the Right to Equality?",
      options: ["Article 14", "Article 19", "Article 21", "Article 32"],
      correctIndex: 0,
      explanation: "Article 14 guarantees equality before the law and equal protection of the laws.",
    },
    {
      id: "law-2",
      topic: "Criminal Law",
      concept: "mens rea",
      question: "What does 'Mens Rea' stand for?",
      options: ["Guilty Act", "Guilty Mind", "Public Law", "Written Code"],
      correctIndex: 1,
      explanation: "Mens Rea is the mental element of a crime—the intention to commit a forbidden act.",
    },
  ],
  "MBA / Business": [
    {
      id: "mba-1",
      topic: "Management",
      concept: "Maslow's hierarchy",
      question: "What is the highest level in Maslow's hierarchy of needs?",
      options: ["Safety", "Self-actualization", "Social belonging", "Esteem"],
      correctIndex: 1,
      explanation: "Self-actualization is the peak of the pyramid, representing the realization of potential.",
    },
  ],
  "Mathematics (1st Grade)": [
    {
      id: "math-g1-1",
      topic: "Arithmetic",
      concept: "single digit addition",
      question: "If you have 4 apples and get 2 more, how many do you have?",
      options: ["5", "6", "7", "4"],
      correctIndex: 1,
      explanation: "4 + 2 = 6.",
    },
  ],
  "Science (6th Grade)": [
    {
      id: "sci-g6-1",
      topic: "Food",
      concept: "sources of energy",
      question: "Which of these is a major source of energy for the body?",
      options: ["Vitamins", "Carbohydrates", "Water", "Minerals"],
      correctIndex: 1,
      explanation: "Carbohydrates provide the main source of fuel (glucose) for our bodies.",
    },
  ],
  "History (9th Grade)": [
    {
      id: "hist-g9-1",
      topic: "World War I",
      concept: "alliances",
      question: "When did World War I end?",
      options: ["1914", "1918", "1939", "1945"],
      correctIndex: 1,
      explanation: "The armistice ending World War I was signed on November 11, 1918.",
    },
  ],
};
