export interface QuizQuestion {
  id: string;
  topic: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const QUIZ_DATA: Record<string, QuizQuestion[]> = {
  DSA: [
    {
      id: "dsa-1",
      topic: "Loops",
      question: "What does a `for` loop with `i = 0; i < 5; i++` execute?",
      options: [
        "5 iterations (0,1,2,3,4)",
        "4 iterations (1,2,3,4)",
        "6 iterations (0,1,2,3,4,5)",
        "Infinite loop",
      ],
      correctIndex: 0,
      explanation: "The loop starts at i=0, runs while i<5, so executes for i = 0,1,2,3,4 — exactly 5 iterations.",
    },
    {
      id: "dsa-2",
      topic: "Loops",
      question: "How do you break out of a loop early in most languages?",
      options: ["continue", "return", "break", "exit"],
      correctIndex: 2,
      explanation: "`break` immediately terminates the current loop. `continue` skips the rest of the current iteration but doesn't exit the loop.",
    },
    {
      id: "dsa-3",
      topic: "Arrays",
      question: "What is the time complexity to access an element at index `i` in an array?",
      options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
      correctIndex: 2,
      explanation: "Arrays store elements in contiguous memory. Accessing index i is a single arithmetic operation (base + i × size) — always O(1).",
    },
    {
      id: "dsa-4",
      topic: "Arrays",
      question: "Given arr = [3, 1, 4, 1, 5], what is arr[2]?",
      options: ["1", "4", "3", "5"],
      correctIndex: 1,
      explanation: "Arrays are 0-indexed. arr[0]=3, arr[1]=1, arr[2]=4. The answer is 4.",
    },
    {
      id: "dsa-5",
      topic: "Sorting",
      question: "What is the average time complexity of QuickSort?",
      options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
      correctIndex: 1,
      explanation: "QuickSort's average case is O(n log n). It partitions the array around a pivot, making ~log n recursive levels each doing O(n) work.",
    },
    {
      id: "dsa-6",
      topic: "Sorting",
      question: "Which sort algorithm is stable and has O(n log n) worst case?",
      options: ["QuickSort", "HeapSort", "MergeSort", "BubbleSort"],
      correctIndex: 2,
      explanation: "MergeSort is stable (preserves order of equal elements) and guarantees O(n log n) in all cases, unlike QuickSort which can degrade to O(n²).",
    },
    {
      id: "dsa-7",
      topic: "Searching",
      question: "Binary search requires the array to be:",
      options: ["Random", "Sorted", "Reversed", "Empty"],
      correctIndex: 1,
      explanation: "Binary search works by repeatedly halving the search space — this is only possible if the array is sorted so we can determine which half contains the target.",
    },
    {
      id: "dsa-8",
      topic: "Variables",
      question: "What is the result of: `let x = '5' + 3` in JavaScript?",
      options: ["8", "53", "'53'", "Error"],
      correctIndex: 2,
      explanation: "In JavaScript, `+` with a string triggers concatenation. '5' + 3 coerces 3 to '3', giving '53'. This is type coercion.",
    },
  ],
  "Web Dev": [
    {
      id: "web-1",
      topic: "HTML Basics",
      question: "Which HTML tag creates a hyperlink?",
      options: ["<link>", "<href>", "<a>", "<url>"],
      correctIndex: 2,
      explanation: "The `<a>` (anchor) tag creates hyperlinks. The `href` attribute specifies the URL. `<link>` is used in `<head>` for stylesheets.",
    },
    {
      id: "web-2",
      topic: "CSS Basics",
      question: "Which CSS property controls text size?",
      options: ["text-size", "font-size", "size", "text-scale"],
      correctIndex: 1,
      explanation: "`font-size` sets the size of the font. Values can be in px, em, rem, %, vw, etc.",
    },
    {
      id: "web-3",
      topic: "JS Basics",
      question: "What does `===` check in JavaScript?",
      options: [
        "Only value equality",
        "Only type equality",
        "Value AND type equality",
        "Reference equality",
      ],
      correctIndex: 2,
      explanation: "`===` is strict equality — checks both value AND type. `==` is loose equality and allows type coercion. Always prefer `===`.",
    },
    {
      id: "web-4",
      topic: "DOM",
      question: "How do you select an element with id='btn' in JavaScript?",
      options: [
        "document.querySelector('.btn')",
        "document.getElementById('btn')",
        "document.getElement('btn')",
        "document.select('#btn')",
      ],
      correctIndex: 1,
      explanation: "`getElementById('btn')` directly targets the element with that ID. You could also use `querySelector('#btn')` which is more flexible.",
    },
    {
      id: "web-5",
      topic: "Flexbox",
      question: "Which CSS property makes elements flex?",
      options: ["display: block", "display: grid", "display: flex", "position: flex"],
      correctIndex: 2,
      explanation: "`display: flex` activates flexbox on the container. Children become flex items automatically.",
    },
    {
      id: "web-6",
      topic: "Events",
      question: "Which event fires when you click a button?",
      options: ["onhover", "onclick", "onpress", "ontap"],
      correctIndex: 1,
      explanation: "The `click` event fires when a user clicks an element. In JS: `element.addEventListener('click', handler)`.",
    },
    {
      id: "web-7",
      topic: "React Basics",
      question: "What is JSX in React?",
      options: [
        "A database query language",
        "A syntax extension that looks like HTML in JavaScript",
        "A CSS preprocessor",
        "A testing framework",
      ],
      correctIndex: 1,
      explanation: "JSX (JavaScript XML) lets you write HTML-like syntax inside JavaScript. Babel compiles it to `React.createElement()` calls.",
    },
    {
      id: "web-8",
      topic: "Fetch/API",
      question: "What does `fetch()` return in JavaScript?",
      options: ["The response data directly", "A Promise", "A callback", "JSON automatically"],
      correctIndex: 1,
      explanation: "`fetch()` returns a Promise that resolves to a Response object. You need `.then(res => res.json())` or `await res.json()` to get the data.",
    },
  ],
  Aptitude: [
    {
      id: "apt-1",
      topic: "Arithmetic",
      question: "What is 15% of 200?",
      options: ["25", "30", "35", "40"],
      correctIndex: 1,
      explanation: "15% of 200 = (15/100) × 200 = 0.15 × 200 = 30.",
    },
    {
      id: "apt-2",
      topic: "Percentages",
      question: "A price increases from 80 to 100. What is the % increase?",
      options: ["20%", "25%", "15%", "30%"],
      correctIndex: 1,
      explanation: "% increase = (New - Old)/Old × 100 = (100-80)/80 × 100 = 20/80 × 100 = 25%.",
    },
    {
      id: "apt-3",
      topic: "Ratios",
      question: "If A:B = 2:3 and B:C = 3:4, what is A:C?",
      options: ["1:2", "2:4", "3:4", "2:3"],
      correctIndex: 1,
      explanation: "A:B = 2:3, B:C = 3:4. A:C = A/B × B/C = (2/3) × (3/4) = 6/12 = 1/2 = 2:4.",
    },
    {
      id: "apt-4",
      topic: "Algebra",
      question: "If 3x + 6 = 21, what is x?",
      options: ["3", "5", "7", "4"],
      correctIndex: 1,
      explanation: "3x + 6 = 21 → 3x = 15 → x = 5.",
    },
    {
      id: "apt-5",
      topic: "Time & Work",
      question: "A can do a job in 10 days, B in 15 days. Together, how many days?",
      options: ["5", "6", "7", "8"],
      correctIndex: 1,
      explanation: "A's rate = 1/10/day, B's = 1/15/day. Together = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6. Time = 6 days.",
    },
    {
      id: "apt-6",
      topic: "Profit & Loss",
      question: "Buy at ₹100, sell at ₹120. What is the profit %?",
      options: ["10%", "20%", "15%", "25%"],
      correctIndex: 1,
      explanation: "Profit = 120 - 100 = 20. Profit % = (20/100) × 100 = 20%.",
    },
    {
      id: "apt-7",
      topic: "Time & Distance",
      question: "Speed = 60 km/h, Distance = 180 km. Time taken?",
      options: ["2 hours", "3 hours", "4 hours", "2.5 hours"],
      correctIndex: 1,
      explanation: "Time = Distance/Speed = 180/60 = 3 hours.",
    },
    {
      id: "apt-8",
      topic: "Probability",
      question: "A bag has 3 red, 2 blue balls. P(red) = ?",
      options: ["2/5", "3/5", "1/2", "3/2"],
      correctIndex: 1,
      explanation: "Total balls = 5. P(red) = 3/5.",
    },
  ],
  "App Dev": [
    {
      id: "app-1",
      topic: "React Native Basics",
      question: "What does React Native primarily let you build?",
      options: ["Only Android games", "Native mobile apps using React concepts", "Only PWAs", "Backend APIs"],
      correctIndex: 1,
      explanation: "React Native lets you build native-feeling mobile apps for iOS and Android using React-style components and JavaScript or TypeScript.",
    },
    {
      id: "app-2",
      topic: "Navigation & Routing",
      question: "Why is navigation important in a mobile app?",
      options: ["It changes your app icon", "It controls movement between screens", "It improves battery health", "It replaces state"],
      correctIndex: 1,
      explanation: "Navigation manages how users move from one screen to another and preserves expected app flow.",
    },
    {
      id: "app-3",
      topic: "UI Components",
      question: "Why use reusable UI components?",
      options: ["To avoid styling entirely", "To make apps slower", "To keep the UI consistent and easier to maintain", "To remove routing"],
      correctIndex: 2,
      explanation: "Reusable components reduce duplication and make visual consistency much easier across screens.",
    },
    {
      id: "app-4",
      topic: "State Management",
      question: "What is state in an app?",
      options: ["The operating system", "Data that changes over time and affects the UI", "A deployment server", "Only API responses"],
      correctIndex: 1,
      explanation: "State is the changing data your UI depends on, like logged-in user info, selected tabs, or fetched content.",
    },
    {
      id: "app-5",
      topic: "Native APIs",
      question: "Which of these is a native API use case?",
      options: ["Reading the camera", "Creating HTML tables", "Compiling CSS", "Running SQL in a browser"],
      correctIndex: 0,
      explanation: "Camera, location, notifications, and storage are classic native-device capabilities exposed through native APIs.",
    },
    {
      id: "app-6",
      topic: "Firebase Integration",
      question: "Firebase is commonly used for:",
      options: ["Phone hardware repair", "Auth, database, and backend services", "Compiling Kotlin only", "Designing icons"],
      correctIndex: 1,
      explanation: "Firebase often provides authentication, databases, storage, and other backend services for mobile apps.",
    },
    {
      id: "app-7",
      topic: "App Store Deployment",
      question: "Before store deployment, you usually need:",
      options: ["No testing", "A stable build and release configuration", "Only a README", "To remove app icons"],
      correctIndex: 1,
      explanation: "Deployment usually needs a production-ready build, signing, metadata, and store-specific release settings.",
    },
    {
      id: "app-8",
      topic: "Performance Optimization",
      question: "A slow mobile screen is usually improved by:",
      options: ["Rendering more unnecessary items", "Reducing extra work and unnecessary re-renders", "Adding more alerts", "Using larger images everywhere"],
      correctIndex: 1,
      explanation: "Performance work usually focuses on rendering less, doing less work per frame, and optimizing expensive operations.",
    },
  ],
  "Data Science": [
    {
      id: "ds-1",
      topic: "Python for Data Science",
      question: "Which language is most commonly used in beginner-friendly data science workflows?",
      options: ["COBOL", "Python", "PHP", "Swift"],
      correctIndex: 1,
      explanation: "Python is widely used because of its strong ecosystem for data manipulation, modeling, and visualization.",
    },
    {
      id: "ds-2",
      topic: "NumPy & Pandas",
      question: "Pandas is mainly used for:",
      options: ["3D game engines", "Tabular data manipulation", "Mobile routing", "CSS preprocessing"],
      correctIndex: 1,
      explanation: "Pandas is designed for table-like data operations such as filtering, grouping, and cleaning datasets.",
    },
    {
      id: "ds-3",
      topic: "Data Visualization",
      question: "Why visualize data before modeling?",
      options: ["To avoid using data", "To detect patterns, outliers, and quality issues", "To skip statistics", "To replace features"],
      correctIndex: 1,
      explanation: "Visualization helps you understand structure, anomalies, and trends before training models.",
    },
    {
      id: "ds-4",
      topic: "Statistics Basics",
      question: "What does mean represent?",
      options: ["The middle value only", "A type of chart", "The average", "The largest observation"],
      correctIndex: 2,
      explanation: "The mean is the arithmetic average of a set of values.",
    },
    {
      id: "ds-5",
      topic: "Machine Learning",
      question: "Machine learning primarily aims to:",
      options: ["Write CSS automatically", "Learn patterns from data to make predictions or decisions", "Replace all databases", "Run only on GPUs"],
      correctIndex: 1,
      explanation: "ML models learn from examples so they can generalize to unseen data.",
    },
    {
      id: "ds-6",
      topic: "Deep Learning",
      question: "Deep learning is most closely associated with:",
      options: ["Spreadsheets only", "Neural networks with multiple layers", "Command line aliases", "Browser routing"],
      correctIndex: 1,
      explanation: "Deep learning refers to multi-layer neural networks that learn hierarchical representations.",
    },
    {
      id: "ds-7",
      topic: "NLP Basics",
      question: "NLP stands for:",
      options: ["Neural Logic Processing", "Natural Language Processing", "Native Learning Pipeline", "Numeric Linear Parsing"],
      correctIndex: 1,
      explanation: "NLP is the field focused on helping computers work with human language.",
    },
    {
      id: "ds-8",
      topic: "Model Deployment",
      question: "A deployed model is one that:",
      options: ["Has been deleted", "Runs in a real product or service", "Only exists in a notebook", "Has no inputs"],
      correctIndex: 1,
      explanation: "Deployment means moving a model from experimentation into a usable application or service.",
    },
  ],
  Cybersecurity: [
    {
      id: "cyber-1",
      topic: "Networking Fundamentals",
      question: "What uniquely identifies a service on a host?",
      options: ["A pixel", "A port", "A cookie", "A variable"],
      correctIndex: 1,
      explanation: "Ports help distinguish network services running on the same machine.",
    },
    {
      id: "cyber-2",
      topic: "Linux & Bash",
      question: "What is Bash primarily used for?",
      options: ["3D modeling", "Command-line interaction and scripting", "Database indexing only", "Design systems"],
      correctIndex: 1,
      explanation: "Bash is a shell used for running commands and automating workflows in terminal environments.",
    },
    {
      id: "cyber-3",
      topic: "Web Security Basics",
      question: "Why is input validation important?",
      options: ["It makes screens brighter", "It helps prevent unsafe data from causing security issues", "It replaces encryption", "It changes DNS"],
      correctIndex: 1,
      explanation: "Validating input reduces risk from malformed or malicious user-controlled data.",
    },
    {
      id: "cyber-4",
      topic: "OWASP Top 10",
      question: "OWASP Top 10 is best described as:",
      options: ["A hardware benchmark", "A list of major web application security risks", "An operating system", "A package manager"],
      correctIndex: 1,
      explanation: "OWASP Top 10 summarizes common and important web application security risks.",
    },
    {
      id: "cyber-5",
      topic: "Nmap Scanning",
      question: "Nmap is commonly used to:",
      options: ["Edit images", "Scan hosts and services", "Compile JavaScript", "Store passwords"],
      correctIndex: 1,
      explanation: "Nmap is a network scanning tool used for discovery and enumeration.",
    },
    {
      id: "cyber-6",
      topic: "Web App Pentesting",
      question: "Pentesting usually tries to:",
      options: ["Improve typography", "Find exploitable weaknesses safely and ethically", "Increase RAM", "Generate invoices"],
      correctIndex: 1,
      explanation: "Pentesting is a controlled security assessment aimed at identifying vulnerabilities.",
    },
    {
      id: "cyber-7",
      topic: "Metasploit Framework",
      question: "Metasploit is primarily known for:",
      options: ["Spreadsheet analysis", "Security exploitation workflows", "Video editing", "iOS design"],
      correctIndex: 1,
      explanation: "Metasploit is a security framework commonly used for exploit development and validation workflows.",
    },
    {
      id: "cyber-8",
      topic: "CTF Challenges",
      question: "CTF usually stands for:",
      options: ["Code Transfer Function", "Capture The Flag", "Central Threat Firewall", "Command Test Flow"],
      correctIndex: 1,
      explanation: "Capture The Flag challenges are hands-on security puzzles used for practice and learning.",
    },
  ],
  IoT: [
    {
      id: "iot-1",
      topic: "Arduino & Raspberry Pi",
      question: "Arduino and Raspberry Pi are commonly used for:",
      options: ["Only graphic design", "Prototyping hardware and connected devices", "Spreadsheet macros only", "Database sharding"],
      correctIndex: 1,
      explanation: "They are popular platforms for learning hardware, prototyping, and embedded projects.",
    },
    {
      id: "iot-2",
      topic: "Sensors & Actuators",
      question: "A sensor primarily:",
      options: ["Displays HTML", "Collects input from the environment", "Stores SQL rows", "Compiles firmware"],
      correctIndex: 1,
      explanation: "Sensors measure things like temperature, motion, light, or pressure from the environment.",
    },
    {
      id: "iot-3",
      topic: "Microcontroller Programming",
      question: "Microcontrollers are best described as:",
      options: ["Small computers embedded inside devices", "Only cloud servers", "Desktop GPUs", "Web browsers"],
      correctIndex: 0,
      explanation: "Microcontrollers are compact programmable chips used to control hardware behavior in embedded systems.",
    },
    {
      id: "iot-4",
      topic: "MQTT & HTTP Protocols",
      question: "MQTT is commonly used in IoT because it is:",
      options: ["A photo format", "Lightweight and messaging-focused", "A CSS library", "A database schema"],
      correctIndex: 1,
      explanation: "MQTT is a lightweight messaging protocol widely used for device-to-device and device-to-cloud communication.",
    },
    {
      id: "iot-5",
      topic: "Edge Computing",
      question: "Edge computing means processing data:",
      options: ["Only in a browser tab", "Closer to the device instead of only in the cloud", "Only after download", "Only on printers"],
      correctIndex: 1,
      explanation: "Edge systems process data near where it is produced, reducing latency and bandwidth usage.",
    },
    {
      id: "iot-6",
      topic: "Cloud IoT Platforms",
      question: "Cloud IoT platforms usually help with:",
      options: ["Font rendering", "Device management and incoming data", "Local battery replacement", "Laptop cooling"],
      correctIndex: 1,
      explanation: "They commonly provide device connectivity, dashboards, data collection, and remote monitoring.",
    },
    {
      id: "iot-7",
      topic: "Real-time Data Streaming",
      question: "Real-time streaming is useful when:",
      options: ["Data can arrive later with no effect", "You need live updates from connected devices", "You never collect data", "The app is offline forever"],
      correctIndex: 1,
      explanation: "Streaming matters when device data needs to be monitored or reacted to continuously.",
    },
    {
      id: "iot-8",
      topic: "IoT Security",
      question: "Why is IoT security especially important?",
      options: ["Devices are never connected", "Connected devices can expose physical systems and networks", "Sensors cannot be attacked", "It only affects battery life"],
      correctIndex: 1,
      explanation: "IoT devices often sit in real environments, so insecure systems can create physical and network-level risk.",
    },
  ],
  Python: [
    {
      id: "py-1",
      topic: "Python Basics & Syntax",
      question: "Which symbol starts a comment in Python?",
      options: ["//", "#", "<!--", "%%"],
      correctIndex: 1,
      explanation: "Python comments start with `#`.",
    },
    {
      id: "py-2",
      topic: "Control Flow",
      question: "Which keyword is used for conditional branching in Python?",
      options: ["switch", "case", "if", "branch"],
      correctIndex: 2,
      explanation: "Python uses `if`, `elif`, and `else` for conditional logic.",
    },
    {
      id: "py-3",
      topic: "Functions",
      question: "How do you define a function in Python?",
      options: ["function hello()", "def hello():", "fn hello()", "create hello()"],
      correctIndex: 1,
      explanation: "Python functions are defined with the `def` keyword followed by a name and parentheses.",
    },
    {
      id: "py-4",
      topic: "OOP in Python",
      question: "A class in Python is used to:",
      options: ["Store CSS", "Define object blueprints", "Deploy apps", "Compile code"],
      correctIndex: 1,
      explanation: "Classes describe the structure and behavior shared by objects.",
    },
    {
      id: "py-5",
      topic: "File I/O",
      question: "Which function is commonly used to open a file in Python?",
      options: ["read()", "file()", "open()", "load()"],
      correctIndex: 2,
      explanation: "The built-in `open()` function is used to work with files.",
    },
    {
      id: "py-6",
      topic: "Modules & Packages",
      question: "Why import a module in Python?",
      options: ["To add reusable functionality", "To increase CPU temperature", "To change the OS", "To avoid variables"],
      correctIndex: 0,
      explanation: "Modules and packages let you organize code and reuse existing functionality.",
    },
    {
      id: "py-7",
      topic: "Decorators & Generators",
      question: "A generator is useful when you want to:",
      options: ["Generate CSS", "Produce values lazily over time", "Encrypt files automatically", "Compile modules"],
      correctIndex: 1,
      explanation: "Generators yield values one at a time, which is helpful for memory-efficient iteration.",
    },
    {
      id: "py-8",
      topic: "Testing & Debugging",
      question: "Why write tests?",
      options: ["To remove all bugs forever", "To verify behavior and catch regressions", "To replace documentation", "To speed up Wi-Fi"],
      correctIndex: 1,
      explanation: "Tests help confirm code behavior and catch changes that break expected functionality.",
    },
  ],
};
