export interface QuizQuestion {
  id: string;
  topic: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const QUIZ_DATA: Record<string, QuizQuestion[]> = {
  DSA: [
    {
      id: "dsa-1",
      topic: "Loops",
      question: "What does a `for` loop with `i = 0; i < 5; i++` execute?",
      options: [
        "5 iterations (0,1,2,3,4)",
        "4 iterations (1,2,3,4)",
        "6 iterations (0,1,2,3,4,5)",
        "Infinite loop",
      ],
      correctIndex: 0,
      explanation: "The loop starts at i=0, runs while i<5, so executes for i = 0,1,2,3,4 — exactly 5 iterations.",
    },
    {
      id: "dsa-2",
      topic: "Loops",
      question: "How do you break out of a loop early in most languages?",
      options: ["continue", "return", "break", "exit"],
      correctIndex: 2,
      explanation: "`break` immediately terminates the current loop. `continue` skips the rest of the current iteration but doesn't exit the loop.",
    },
    {
      id: "dsa-3",
      topic: "Arrays",
      question: "What is the time complexity to access an element at index `i` in an array?",
      options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
      correctIndex: 2,
      explanation: "Arrays store elements in contiguous memory. Accessing index i is a single arithmetic operation (base + i × size) — always O(1).",
    },
    {
      id: "dsa-4",
      topic: "Arrays",
      question: "Given arr = [3, 1, 4, 1, 5], what is arr[2]?",
      options: ["1", "4", "3", "5"],
      correctIndex: 1,
      explanation: "Arrays are 0-indexed. arr[0]=3, arr[1]=1, arr[2]=4. The answer is 4.",
    },
    {
      id: "dsa-5",
      topic: "Sorting",
      question: "What is the average time complexity of QuickSort?",
      options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
      correctIndex: 1,
      explanation: "QuickSort's average case is O(n log n). It partitions the array around a pivot, making ~log n recursive levels each doing O(n) work.",
    },
    {
      id: "dsa-6",
      topic: "Sorting",
      question: "Which sort algorithm is stable and has O(n log n) worst case?",
      options: ["QuickSort", "HeapSort", "MergeSort", "BubbleSort"],
      correctIndex: 2,
      explanation: "MergeSort is stable (preserves order of equal elements) and guarantees O(n log n) in all cases, unlike QuickSort which can degrade to O(n²).",
    },
    {
      id: "dsa-7",
      topic: "Searching",
      question: "Binary search requires the array to be:",
      options: ["Random", "Sorted", "Reversed", "Empty"],
      correctIndex: 1,
      explanation: "Binary search works by repeatedly halving the search space — this is only possible if the array is sorted so we can determine which half contains the target.",
    },
    {
      id: "dsa-8",
      topic: "Variables",
      question: "What is the result of: `let x = '5' + 3` in JavaScript?",
      options: ["8", "53", "'53'", "Error"],
      correctIndex: 2,
      explanation: "In JavaScript, `+` with a string triggers concatenation. '5' + 3 coerces 3 to '3', giving '53'. This is type coercion.",
    },
  ],
  "Web Dev": [
    {
      id: "web-1",
      topic: "HTML Basics",
      question: "Which HTML tag creates a hyperlink?",
      options: ["<link>", "<href>", "<a>", "<url>"],
      correctIndex: 2,
      explanation: "The `<a>` (anchor) tag creates hyperlinks. The `href` attribute specifies the URL. `<link>` is used in `<head>` for stylesheets.",
    },
    {
      id: "web-2",
      topic: "CSS Basics",
      question: "Which CSS property controls text size?",
      options: ["text-size", "font-size", "size", "text-scale"],
      correctIndex: 1,
      explanation: "`font-size` sets the size of the font. Values can be in px, em, rem, %, vw, etc.",
    },
    {
      id: "web-3",
      topic: "JS Basics",
      question: "What does `===` check in JavaScript?",
      options: [
        "Only value equality",
        "Only type equality",
        "Value AND type equality",
        "Reference equality",
      ],
      correctIndex: 2,
      explanation: "`===` is strict equality — checks both value AND type. `==` is loose equality and allows type coercion. Always prefer `===`.",
    },
    {
      id: "web-4",
      topic: "DOM",
      question: "How do you select an element with id='btn' in JavaScript?",
      options: [
        "document.querySelector('.btn')",
        "document.getElementById('btn')",
        "document.getElement('btn')",
        "document.select('#btn')",
      ],
      correctIndex: 1,
      explanation: "`getElementById('btn')` directly targets the element with that ID. You could also use `querySelector('#btn')` which is more flexible.",
    },
    {
      id: "web-5",
      topic: "Flexbox",
      question: "Which CSS property makes elements flex?",
      options: ["display: block", "display: grid", "display: flex", "position: flex"],
      correctIndex: 2,
      explanation: "`display: flex` activates flexbox on the container. Children become flex items automatically.",
    },
    {
      id: "web-6",
      topic: "Events",
      question: "Which event fires when you click a button?",
      options: ["onhover", "onclick", "onpress", "ontap"],
      correctIndex: 1,
      explanation: "The `click` event fires when a user clicks an element. In JS: `element.addEventListener('click', handler)`.",
    },
    {
      id: "web-7",
      topic: "React Basics",
      question: "What is JSX in React?",
      options: [
        "A database query language",
        "A syntax extension that looks like HTML in JavaScript",
        "A CSS preprocessor",
        "A testing framework",
      ],
      correctIndex: 1,
      explanation: "JSX (JavaScript XML) lets you write HTML-like syntax inside JavaScript. Babel compiles it to `React.createElement()` calls.",
    },
    {
      id: "web-8",
      topic: "Fetch/API",
      question: "What does `fetch()` return in JavaScript?",
      options: ["The response data directly", "A Promise", "A callback", "JSON automatically"],
      correctIndex: 1,
      explanation: "`fetch()` returns a Promise that resolves to a Response object. You need `.then(res => res.json())` or `await res.json()` to get the data.",
    },
  ],
  Aptitude: [
    {
      id: "apt-1",
      topic: "Arithmetic",
      question: "What is 15% of 200?",
      options: ["25", "30", "35", "40"],
      correctIndex: 1,
      explanation: "15% of 200 = (15/100) × 200 = 0.15 × 200 = 30.",
    },
    {
      id: "apt-2",
      topic: "Percentages",
      question: "A price increases from 80 to 100. What is the % increase?",
      options: ["20%", "25%", "15%", "30%"],
      correctIndex: 1,
      explanation: "% increase = (New - Old)/Old × 100 = (100-80)/80 × 100 = 20/80 × 100 = 25%.",
    },
    {
      id: "apt-3",
      topic: "Ratios",
      question: "If A:B = 2:3 and B:C = 3:4, what is A:C?",
      options: ["1:2", "2:4", "3:4", "2:3"],
      correctIndex: 1,
      explanation: "A:B = 2:3, B:C = 3:4. A:C = A/B × B/C = (2/3) × (3/4) = 6/12 = 1/2 = 2:4.",
    },
    {
      id: "apt-4",
      topic: "Algebra",
      question: "If 3x + 6 = 21, what is x?",
      options: ["3", "5", "7", "4"],
      correctIndex: 1,
      explanation: "3x + 6 = 21 → 3x = 15 → x = 5.",
    },
    {
      id: "apt-5",
      topic: "Time & Work",
      question: "A can do a job in 10 days, B in 15 days. Together, how many days?",
      options: ["5", "6", "7", "8"],
      correctIndex: 1,
      explanation: "A's rate = 1/10/day, B's = 1/15/day. Together = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6. Time = 6 days.",
    },
    {
      id: "apt-6",
      topic: "Profit & Loss",
      question: "Buy at ₹100, sell at ₹120. What is the profit %?",
      options: ["10%", "20%", "15%", "25%"],
      correctIndex: 1,
      explanation: "Profit = 120 - 100 = 20. Profit % = (20/100) × 100 = 20%.",
    },
    {
      id: "apt-7",
      topic: "Time & Distance",
      question: "Speed = 60 km/h, Distance = 180 km. Time taken?",
      options: ["2 hours", "3 hours", "4 hours", "2.5 hours"],
      correctIndex: 1,
      explanation: "Time = Distance/Speed = 180/60 = 3 hours.",
    },
    {
      id: "apt-8",
      topic: "Probability",
      question: "A bag has 3 red, 2 blue balls. P(red) = ?",
      options: ["2/5", "3/5", "1/2", "3/2"],
      correctIndex: 1,
      explanation: "Total balls = 5. P(red) = 3/5.",
    },
  ],
};
